name: Upload File to Release
author: Ethirix
description: 'Uploads a file to a tagged release. Requires `contents: write` permissions.'

inputs:
  tag:
    description: 'Release tag to upload file to, e.g. v1.5.2'
    required: true
  file:
    description: 'Path to file to be uploaded, e.g. ./artefacts/build.tar.gz'
    required: true
  token:
    description: 'GitHub Token required to use `gh`, e.g. secrets.GITHUB_TOKEN'
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v7
      with:
        clean: 'false'
      
    - name: "Upload to Release"
      shell: bash
      run: gh release upload ${{ inputs.tag }} ${{ inputs.file }}

      env:
        GH_TOKEN: ${{ inputs.token }}