name: Build CMake Project with Presets
description: 'Configurers and builds a CMake Preset in the form: target-architecture-compiler[-build-type]. Requires `contents: read` permissions.'

inputs:
  target:
    description: 'What the target platform is for the build, e.g. win or linux'
    required: true
  architecture:
    description: 'Target architecture for compilation, e.g. x64 or x86'
    required: true
  compiler:
    description: 'What compiler should be used for C/C++, e.g. gcc or mingw64'
    required: true
  build-type:
    description: 'What is the build configuration, e.g. release or debug'
    required: true

runs:
  using: composite
    
  steps:
    - uses: actions/checkout@v7

    - name: Initialise Runner
      shell: bash
      run: |
        sudo apt remove cmake -y
        sudo pip install cmake --upgrade
        if [ ${{ inputs.target }} == "win" ]; then
          if [ ${{ inputs.architecture }} == "x64" ]; then
            sudo apt install gcc-mingw-w64-x86-64
            sudo apt install g++-mingw-w64-x86-64
          else
            sudo apt install gcc-mingw-w64-i686
            sudo apt install g++-mingw-w64-i686
          fi
        else
          sudo apt install gcc-multilib
          sudo apt install g++-multilib
        fi
        
    - name: CMake Configure
      if: success()
      shell: bash
      run: cmake --preset ${{ inputs.target }}-${{ inputs.architecture }}-${{ inputs.compiler }}

    - name: CMake Build
      if: success()
      shell: bash
      run: cmake --build --preset ${{ inputs.target }}-${{ inputs.architecture }}-${{ inputs.compiler }}-${{ inputs.build-type }}