name: Build CMake Project with Presets
permissions:
  contents: read
  
on:
  workflow_call: 
    inputs: 
      build-tool:
        description: 'Build tool for CMake to use, e.g. ninja'
        required: true
        type: string
      compiler:
        description: 'What compiler should be used for C/C++, e.g. gcc'
        required: true
        type: string
      architecture:
        description: "Target architecture for compilation, e.g. x64 or x86"
        required: true
        type: string
      target:
        description: "What the target platform is for the build, e.g. win or linux"
        required: true
        type: string
      build-type:
        description: "What is the build configuration, e.g. debug or release"
        required: true
        type: string
        
jobs: 
  build-cmake-project:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Initialise Runner
        shell: bash
        run: |
          sudo apt remove cmake -y
          sudo pip install cmake --upgrade
          sudo apt install gcc-multilib
          sudo apt install g++-multilib
          
      - name: CMake Configure
        shell: bash
        run:
          cmake -S "${{ github.workspace }}"
          --preset ${{ inputs.build-tool }}-${{ inputs.compiler }}-${{ inputs.architecture }}-${{ inputs.target }}

      - name: CMake Build
        shell: bash
        run:
          cmake --build
          --preset ${{ inputs.build-tool }}-${{ inputs.compiler }}-${{ inputs.architecture }}-${{ inputs.target }}-${{ inputs.build-type }}
      